### ISSUE TITLE
Witness sign should normalize input

### ISSUE THREAD

**Issue by colek42** [testifysec/witness#153]
`witness sign` currently accepts YAML and JSON.

Should we normalize this to JSON when we store it in the envelope?

**Comment by mikhailswift** [comment]
I don't think Witness sign should modify what it's signing at all.  The `witness sign` cli can theoretically be used to sign any arbitrary file regardless of encoding.  This is both a benefit and a con, since we don't do any data validation prior to signing the document -- which would be very useful when signing things like Witness policy documents.

Something we may be able to do is look at the payload type being signed and if it is one we recognize attempt to validate the data.  I'm a bit hesitant to normalize/modify any data being signed.  I know canonicalization is a common thing for this type of work so I'm not incredibly opposed, however.

If we do any form of canonicalization or normalization of data being signed I would prefer to maintain whatever markup language was input.  So if we're fed JSON we should output JSON, etc.
